package com.richdev.firstkotlinprogram

fun main(args: Array<String>) {
    val age = ArrayList<Int>()
    age.add(10)
    age.add(1, 15)
    age.add(2, 20)
    println("First element of age ArrayList = " + age[0])
    println("Second element of age ArrayList = " + age.get(1))
    println("Third element of age ArrayList = ${age[2]}")
    println("-------------------------------------------------")
    age.remove(15)
    println(age.size)
    println("First element of age ArrayList = " + age[0])
    println("Second element of age ArrayList = " + age.get(1))
    println("-------------------------------------------------")
    val cars = arrayListOf<String>("Opel", "MBW")
    cars.add("Ford")
    println("First element of cars ArrayList = " + cars[0])
    println("Second element of cars ArrayList = " + cars.get(1))
    println("Third element of cars ArrayList = ${cars[2]}")
    println("-------------------------------------------------")
    val myMixArrayList = ArrayList<Any>()
    myMixArrayList.add("Ford")
    myMixArrayList.add(5)
    myMixArrayList.add(2.5)
    myMixArrayList.add(false)
    myMixArrayList.add("K")
    println("First element of myMixArrayList ArrayList = " + myMixArrayList[0])
    println("Second element of myMixArrayList ArrayList = " + myMixArrayList.get(1))
    println("Third element of myMixArrayList ArrayList = ${myMixArrayList[2]}")
    println("Fourth element of myMixArrayList ArrayList = ${myMixArrayList[3]}")
    println("Fifth element of myMixArrayList ArrayList = ${myMixArrayList[4]}")
}